// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fsoejovbbbzhuuxksrwo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZzb2Vqb3ZiYmJ6aHV1eGtzcndvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4MjA4NzIsImV4cCI6MjA2MDM5Njg3Mn0.aNFj1E7ttDqaARkRcMtY595i_N-ysmdfjO1-9QjpniQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);